### ISSUE TITLE
Request for Fedora 28

### ISSUE THREAD

**Issue by gfrenoy** [packpack/packpack#102]
Hi all,

Any chance to have [fedora-28](https://fedoramagazine.org/announcing-fedora-28/) on the packpack [docker hub](https://hub.docker.com/r/packpack/packpack/tags/) ?

Or maybe some instructions or even a small tip to build such an image ?

Thanks for your great project that is really helping us a lot (https://github.com/asbru-cm/asbru-cm) ; this request is acually a follow up of https://github.com/asbru-cm/asbru-cm/issues/106.

**Comment by knight-of-ni** [comment]
The f28 dockerfile is here:
https://github.com/packpack/packpack-docker-images/tree/master/fedora/28

You can use this as a template for future versions of fedora.

Build it like any other dockerfile and optionally push it to your own dockerhub repo. That's what I've been doing.

**Comment by Totktonada** [comment]
Added to the Docker Hub: https://hub.docker.com/r/packpack/packpack/tags/
