### ISSUE TITLE
packpack el8 - cannot install the best candidate for the job

### ISSUE THREAD

**Issue by knight-of-ni** [packpack/packpack#115]
Thanks to the introduction of modules in el8, many applications are suffering from dnf failures to find the right packages.

El8 builds were failing for the ZoneMinder project. Error text is at the bottom of this message.

Adding the following lines to the el8 dockerfile works around the issue and lets our builds succeed:
```
RUN echo "module_hotfixes=1" >> /etc/dnf/dnf.conf
RUN echo "best=0" >> /etc/dnf/dnf.conf
```

The full modified dockerfile can be seen here:
https://github.com/ZoneMinder/zmdockerfiles/blob/master/buildsystem/el-8/Dockerfile

I do not know for certain whether this workaround will have any negative side affects for others. However, I thought I'd post the workaround here, as it seems likely others will run into this issue.

```
Package perl-podlators-4.11-1.el8.noarch is already installed.
Error: 
 Problem 1: cannot install the best candidate for the job
  - package perl-Archive-Tar-2.30-1.module_el8.0.0+50+c3b345cd.noarch is excluded
 Problem 2: cannot install the best candidate for the job
  - package perl-Sys-Syslog-0.35-397.module_el8.0.0+50+c3b345cd.x86_64 is excluded
 Problem 3: cannot install the best candidate for the job
  - package perl-generators-1.10-7.module_el8.0.0+50+c3b345cd.noarch is excluded
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Last metadata expiration check: 0:00:02 ago on Tue Dec 24 04:38:37 2019.
Package cmake-3.11.4-3.el8.x86_64 is already installed.
Package coreutils-single-8.30-6.el8.x86_64 is already installed.
Package findutils-1:4.6.0-20.el8.x86_64 is already installed.
Package gcc-8.2.1-3.5.el8.x86_64 is already installed.
Package gcc-c++-8.2.1-3.5.el8.x86_64 is already installed.
Package gzip-1.9-4.el8.x86_64 is already installed.
Package perl-generators-1.10-7.el8.noarch is already installed.
Package perl-podlators-4.11-1.el8.noarch is already installed.
Error: 
 Problem 1: cannot install the best candidate for the job
  - package perl-Archive-Tar-2.30-1.module_el8.0.0+50+c3b345cd.noarch is excluded
 Problem 2: cannot install the best candidate for the job
  - package perl-Sys-Syslog-0.35-397.module_el8.0.0+50+c3b345cd.x86_64 is excluded
 Problem 3: cannot install the best candidate for the job
  - package perl-generators-1.10-7.module_el8.0.0+50+c3b345cd.noarch is excluded
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
make: *** [/pack//rpm.mk:123: package] Error 1
```

**Comment by Totktonada** [comment]
Thanks for the report!

@printercu seen this too on https://github.com/tarantool/cartridge-cli when /usr/bin/prove was on dependencies list.

I had hope that the problem will be resolved on CentOS / RedHat side, but it seems it was not. So it seems we should work it around on our side.

AFAIU `best=0` should be enough.

The upstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1756681

**Comment by Totktonada** [comment]
I was hit by the problem myself during work on [tarantool/tarantool-php](https://github.com/tarantool/tarantool-php) [packages](https://github.com/tarantool/tarantool-php/issues/117). Rebuilt the CentOS 8 image w/o any changes and the problem gone.

Pushed the rebuilt image.

Hope it was fixed on CentOS 8 side. Feel free to reopen the issue if you'll hit by the problem on CentOS 8 or a recent Fedora version.
