### ISSUE TITLE
Support for Debian 11 (bullseye)

### ISSUE THREAD

**Issue by amdei** [packpack/packpack#133]
Hello,

It would be great to have ability to run packpack to build targets for Debain 11 (Bullseye).

Debian 11 is (well, soon to be) almost out, and it would be great to have ability to test software (e.g. Tarantool) on Debian 11

**Comment by Totktonada** [comment]
Seems resolved in https://github.com/packpack/packpack-docker-images/pull/65. Feel free to reopen, if I missed something.
