### ISSUE TITLE
`/pack//deb.mk:124: recipe for target '/build/*.changes' failed`

### ISSUE THREAD

**Issue by Jeckerson** [packpack/packpack#137]
Currently, we are trying to migrate from Travis, due their limitations, to Github Actions.

But this error occurs:
```
/pack//deb.mk:124: recipe for target '/build/php-phalcon_4.1.2-1057886818+php7.3_amd64.changes' failed
```

https://github.com/phalcon/packagecloud/pull/71/checks?check_run_id=3138959223#step:13:186

**Comment by Totktonada** [comment]
Looked briefly.

It seems, there is no `debian/control`: https://sources.debian.org/src/devscripts/2.21.3/scripts/mk-build-deps.pl/#L256

I see that `debian/control` is generated from the [ci/prepare-debian.sh](https://github.com/phalcon/packagecloud/blob/5853b9ab1debd7566ddd5f5dd1b7cd3d1357c01e/ci/prepare-debian.sh) and, it seems, it was not generated or was not included into the tarball.

The tarball includes everything that is tracked by git (collected by `git ls-files`), so we should at least add a file (`git add`) to get it included into the tarball. Maybe something went wrong here.

**Comment by Totktonada** [comment]
Ouch, I didn't reload the page :)

**Comment by Jeckerson** [comment]
Yeah, sorry, didn't included all steps of pipeline, which were detected after good sleep.

What was missing:
```
  - if [ $OS != "el" ]; then ./ci/prepare-debian.sh; fi
  - if [ $OS = "el" ]; then ./ci/prepare-rpm.sh; fi
```
