### ISSUE TITLE
Allow building zoneminder on Ubuntu Jammy

### ISSUE THREAD

**Issue by ben-rambam** [packpack/packpack#144]
Zoneminder won't build on Ubuntu Jammy because it has to install tzdata which asks for the timezone from the user. This could be solved multiple ways:

1. Preinstall tzdata in the ubuntu-jammy docker image (This is how previous ubuntu versions were)
2. Re-enable  `PRESERVE_ENVVARS` so `TZ` and `DEBIAN_FRONTEND` can be passed into the container
3. Add the `-i` flag to the `docker run` command so that users can interactively select the timezone (This will require cleaning the build directory for some reason)

For method 2 you would need the following:

I've verified that it can be installed in a non-interactive way by running as root:
`DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y tzdata`

Or, if you aren't root, you can run:
`DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo -E apt install -y tzdata`

**Comment by Totktonada** [comment]
Preinstallation is only temporary/partial solution, I guess:

* The `tzdata` package can be updated (will it as for interactive configuration again?).
* Another interactive package may be pulled into dependencies or installed in `prebuild.sh`. I know that `postfix` wants interactive configuration.

Whether `tzdata` is in your dependencies in `debian/control` or pulled by something in `prebuild.sh`? If the former is true, I hope 194f898750cbbee6dd35255fe8aa7ec878eb3836 will help. If the latter is your case, add `export DEBIAN_FRONTEND=noninteractive` to your `prebuild.sh`.

**Comment by ben-rambam** [comment]
This issue was indeed fixed by https://github.com/packpack/packpack/commit/194f898750cbbee6dd35255fe8aa7ec878eb3836
