### ISSUE TITLE
Support packpack in local docker images

### ISSUE THREAD

**Issue by elhimov** [packpack/packpack#154]
It would be convenient to have an option to run packpack in local docker image instead of pulling it from some docker registry.

**Comment by elhimov** [comment]
> Sure. I'm commenting the following line when performing testing before pushing the images.
> 
> https://github.com/packpack/packpack/blob/cb464c910cd4808100de7b83a024c39567a14982/packpack#L204
> 
> All the other settings are passed using environment variables, so I propose to add one more.

`docker run` pull the image automatically if needed, so w/o explicit `docker pull` command we will got the desired behavior: if image exists locally it is used and pulled from registry otherwise. I've prepared a [PR](https://github.com/packpack/packpack/pull/156)

**Comment by Totktonada** [comment]
> `docker run` pull the image automatically if needed, so w/o explicit `docker pull` command we will get the desired behavior: if image exists locally it is used and pulled from the registry otherwise. I've prepared a [PR](https://github.com/packpack/packpack/pull/156)

It doesn't update the image if it is updated in the remote registry. I've commented it in the pull request. Let's continue the discussion in the PR.
