### ISSUE TITLE
Consider installing doxygen with --no-install-recommends

### ISSUE THREAD

**Issue by gdevenyi** [packpack/packpack#17]
Just noticed that doxygen recommends the whole texlive distribution which is *huge*.

It's probably not needed for what doxygen is being used for in builds, but I'm not sure.

**Comment by rtsisyk** [comment]
Makes sense. I usually set "install-recommends" to false globally on my Debian hosts:

```
$ cat /etc/apt/apt.conf.d/00recommended 
apt::install-recommends "false";
```
