### ISSUE TITLE
debuild options are position dependent

### ISSUE THREAD

**Issue by gdevenyi** [packpack/packpack#25]
My envvar and path "fixes" are still broken because options are position dependent

https://lists.debian.org/debian-dpkg/2011/03/msg00087.html

I'm on moving them to the right place.

**Comment by gdevenyi** [comment]
Not cool: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=311434

**Comment by rtsisyk** [comment]
Fixed by f7ae60a438f3b6e8bf05dcdc61aea444b23d2ed3
