### ISSUE TITLE
Pre-build command hooks

### ISSUE THREAD

**Issue by julianscheel** [packpack/packpack#3]
I couldn't find a way to add commands that shall be executed in the docker container before the actual package build starts. This can be helpful if this is used to build a package which has dependencies which are not met by the default distribution repositories. In my specific case I'd need to add a ppa to ubuntu:xenial before starting the debuild step.

**Comment by rtsisyk** [comment]
> I couldn't find a way to add commands that shall be executed in the docker container before the actual package build starts. 

PackPack tries to read `.build.mk` Makefile at the root directory of your repository to override Make targets, but this feature isn't documented yet. Your feature request makes sense, I'll take a look.

> In my specific case I'd need to add a ppa to ubuntu:xenial before starting the debuild step.

We usually patched Dockerfiles for this case.

**Comment by benoit-pierre** [comment]
I have the same issue, I worked around it by invoking `packpack` like this:
```shell
OS='ubuntu' DIST='trusty' packpack -f /source/linux/packpack.mk ubuntu_package
```
With this in `linux/packpack.mk`:
```make
.PHONY: ubuntu_package
.NOTPARALLEL: ubuntu_package

ubuntu_package: ubuntu_bootstrap package

ubuntu_bootstrap:
        sudo apt-get -y install software-properties-common
        sudo add-apt-repository -y ppa:benoit.pierre/plover
```

**Comment by julianscheel** [comment]
> PackPack tries to read .build.mk Makefile at the root directory of your repository to override Make targets, but this feature isn't documented yet.

I saw that one by digging in the sources, but it didn't really feel like a matching entrypoint for tweaking the host-config.

> We usually patched Dockerfiles for this case.

This is what I did as well for now, but having a simple hook would be easier for most cases.

**Comment by gdevenyi** [comment]
I could use this feature to address #46 and #47 locally for my builds.

**Comment by rtsisyk** [comment]
I see that @knnniggett uses [the same approach](https://github.com/ZoneMinder/ZoneMinder/blob/master/utils/packpack/redhat_package.mk) as @benoit-pierre. Any ideas how to fix this problems universally for everybody?

**Comment by knnniggett** [comment]
I don't have a better solution to the problem at the moment, but if I encounter new information I will certainly post it.

**Comment by sergeyklay** [comment]
It is implemented. Take a look for example for Debian/Unbuntu:

https://github.com/packpack/packpack/blob/30ff7b51654c19b8919d01ca8d4aa480e87e8241/pack/deb.mk#L40-L77

cc @rtsisyk

**Comment by Totktonada** [comment]
@rtsisyk Can be closed?
