### ISSUE TITLE
Fedora 24 locale different than other dockers

### ISSUE THREAD

**Issue by gdevenyi** [packpack/packpack#30]
https://github.com/packpack/packpack/blob/master/docker/fedora24/Dockerfile#L11

I think C env makes more sense overall than en_US?

**Comment by rtsisyk** [comment]
New fedora containers (fedora/24 and fedora/rawhide) doesn't include en_US.UTF-8 locale anymore.

**Comment by gdevenyi** [comment]
Perhaps the C locale is the best choice anyways?
