### ISSUE TITLE
Figure out how to supply newer cmake

### ISSUE THREAD

**Issue by gdevenyi** [packpack/packpack#35]
Many packages may be buildable with cmake (other dependencies satisfied) but need a newer cmake to build.

Ubuntu has a ppa to handle this.

How might we handle this with debian/centos?

**Comment by rtsisyk** [comment]
Debian and Ubuntu have backports. 
CentOS has devtoolset.

Which version of CMake do you need? I can try to resolve this problem.

**Comment by rtsisyk** [comment]
@gdevenyi Do you have some other dependencies for your project which are not listed in the Dockerfiles?

**Comment by rtsisyk** [comment]
I think about splitting Docker images into a separate repository...

**Comment by gdevenyi** [comment]
Right now, the only thing missing for olders stuff is cmake > 3.1

**Comment by gdevenyi** [comment]
** cmake >= 3.1

**Comment by rtsisyk** [comment]
- [ ] Debian Wheezy
- [x] Debian Jessie 
- [x] Debian Stretch
- [x] Debian Sid
- [ ] Ubuntu Precise
- [ ] Ubuntu Trusty
- [x] Ubuntu Xenial
- [x] Ubuntu Yaketty
- [x] CentOS 6
- [x] CentOS 7
- [x] Fedora 23
- [x] Fedora 24

**Comment by rtsisyk** [comment]
Precise, Trusty and Wheezy remains.
For CentOS6/7 please add cmake3 to BuildRequires.

**Comment by gdevenyi** [comment]
Precise and Trusty should already be okay, see https://github.com/packpack/packpack/blob/master/docker/ubuntu-trusty/Dockerfile#L17 and https://github.com/packpack/packpack/blob/master/docker/ubuntu-precise/Dockerfile#L20

I patched those in a while ago

**Comment by rtsisyk** [comment]
OK, wheezy remains.

**Comment by rtsisyk** [comment]
I've tried cmake package from Ubuntu Precise and Debian Trusty on Wheezy - both requires new libc...

**Comment by rtsisyk** [comment]
I can't even build it from the source package:

```
dpkg-checkbuilddeps: Unmet build dependencies: debhelper (>= 9.20160114~) dpkg-dev (>= 1.17.14~) libbz2-dev libcurl4-openssl-dev | libcurl-ssl-dev libjsoncpp-dev liblzma-dev libncurses5-dev qtbase5-dev

# apt-cache policy debhelper
debhelper:
  Installed: 9.20120909
  Candidate: 9.20120909

apt-cache policy dpkg-dev
dpkg-dev:
  Installed: 1.16.18
  Candidate: 1.16.18
  Version table:
 *** 1.16.18 0
        500 http://deb.debian.org/debian/ wheezy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by rtsisyk** [comment]
I re-build Ubuntu Precise PPA for Debian Wheezy: https://packagecloud.io/packpack/backports
 
![wheezy](https://cloud.githubusercontent.com/assets/1799054/20321462/f8550a1c-ab8e-11e6-92f6-02a0c959eb03.gif)

**Comment by gdevenyi** [comment]
Amazing!
