### ISSUE TITLE
Centos doesn't know what C locale is

### ISSUE THREAD

**Issue by gdevenyi** [packpack/packpack#41]
:(

Continued spamming of:
```
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
```

**Comment by gdevenyi** [comment]
It looks like libc didn't supply a C.UTF-& locale back in the day:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=636086

**Comment by rtsisyk** [comment]
Oh my bad, I'll change it back to en_US.UTF-8.

**Comment by gdevenyi** [comment]
No problem, I suggested it in the first place :)
