### ISSUE TITLE
cmake for ubuntu-precise missing SSL support

### ISSUE THREAD

**Issue by gdevenyi** [packpack/packpack#46]
From this ppa:
https://github.com/packpack/packpack/blob/master/docker/ubuntu-precise/Dockerfile#L20

Sadly SSL support is missing from cmake so it can't do any https downloads:
```
    for file: [/build/minc-toolkit-v2-0.0.1/obj-x86_64-linux-gnu/man-pages/minc-man-pages-0.1.00.tar.gz]
      expected hash: [8b8cc666cda80b5b96c242b17b084c27]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [1;"Unsupported protocol"]
```

Perhaps you can do your magic again and do a backport from another source?

**Comment by rtsisyk** [comment]
See #47.
