### ISSUE TITLE
cmake backport in #35 is missing SSL support

### ISSUE THREAD

**Issue by gdevenyi** [packpack/packpack#47]
Same as backport issue in #46 

Needs something like libcurl4-gnutls-dev during build?

```
Make Error at man-pages/CMakeLists.txt:4 (file):
  file DOWNLOAD HASH mismatch

    for file: [/build/minc-toolkit-v2-1.9.14/obj-x86_64-linux-gnu/man-pages/minc-man-pages-0.1.00.tar.gz]
      expected hash: [8b8cc666cda80b5b96c242b17b084c27]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [1;"Unsupported protocol"]


```

**Comment by rtsisyk** [comment]
It was terrible idea to manually update CMake in Debian/Ubuntu. It worked for x86_64, but there is no easy way to support these hacks on all architectures (see #52).  Please consider to exclude distributions with old CMake, gcc and other unsatisfied dependencies from your build matrix.

**Comment by gdevenyi** [comment]
Okay, we'll just have to stop providing builds for those systems. Thanks.
