### ISSUE TITLE
Wishlish: 32bit versions

### ISSUE THREAD

**Issue by gdevenyi** [packpack/packpack#52]
For our builds we would still like to support 32bit legacy systems. Hopefully this is as easy as creating 32bit docker versions?

**Comment by rtsisyk** [comment]
Docker promises to relases multi-arch Docker Hub every year. I want to experiment with  armhf and aarch64 architectures. I think that on success i386 can be added too.

https://hub.docker.com/u/armhf/
https://hub.docker.com/u/aarch64/
https://hub.docker.com/u/i386/

**Comment by gdevenyi** [comment]
For me, I can get a 32bit image working:
```
docker pull ggrandes/ubuntu32
docker run -it --name="test32" ggrandes/ubuntu32 /bin/bash
> file /bin/bash
/bin/bash: ELF 32-bit LSB  executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=4ead65aeca4e9f1eabf3a0d63eb1f96c225b25fd, stripped
```

So, we're some of the way there. I guess there aren't official images yet.
