### ISSUE TITLE
Regression with %autosetup support

### ISSUE THREAD

**Issue by knnniggett** [packpack/packpack#59]
All our rpm builds began failing recently, and I tracked it back to a recent change in rpm.mk

#55 added support for the rpm %autosetup macro. The sed command looked like this:
`-e 's/%autosetup -n .*/%autosetup -n $(PRODUCT)-$(VERSION)/' \`

This command would change %prep from this:
```
%prep
%autosetup -n %{name}-%{version}
%autosetup -a 1
```
to something like this:
```
%prep
%autosetup -n zoneminder-1.0.85
%autosetup -a 1
```

Since the "-n" flag is optional, it would also safely make no changes at all if %autosetup is called without it.

The regex only matched the first instance of %autosetup, which is what we want.

Recently, commit 5b91b4b0a3dfd8d3bd02e3e8e2701310f1b6eedd changed the line in question to:
`-e 's/%autosetup.*/%autosetup -n $(PRODUCT)-$(VERSION)/' \`

The problem with this is that the regex now matches both/all mentions of the %autosetup macro, when we only want it to match the first.  For example %prep is changed to look like this:
```
%prep
%autosetup -n zoneminder-1.0.85
%autosetup -n zoneminder-1.0.85
```
Naturally, this causes the rpm build to fail.

Any spec file which uses the %autosetup macro and has one or more git submodules, requires multiple calls to %autosetup.

I didn't look too deeply into why this line was changed. I am hopeful it can be changed back w/o breaking something else.

**Comment by knnniggett** [comment]
Perhaps the best solution in this case would be to tell sed to replace only the first occurrence.

Looks like this might work (gnu sed only):
`-e '0,/%autosetup.*/s/%autosetup.*/%autosetup -n $(PRODUCT)-$(VERSION)/' \`

Haven't test it yet. Will try when I have a moment.

**Comment by rtsisyk** [comment]
Sorry, I've broken `%autosetup` trying to fix ZoneMinder :) I'll try to avoid such careless changes the next time. Pushed, thank you for your patience!

**Comment by knnniggett** [comment]
Hey, no problem. Thanks for merging that pr.
I'm working on an unrelated issue with Travis deployment right now. Once I resolve that, I will followup with #58.
