### ISSUE TITLE
New feature request: Alpine

### ISSUE THREAD

**Issue by sergeyklay** [packpack/packpack#64]
Hello, any plans about Alpine packaging?

Thanks

**Comment by rtsisyk** [comment]
Alpine Linux is in the short list. I just don't have enough time to implement it now.
It should be easy to add new makefile for Alpine:

- Add alpine.mk which will detect APKBUILD in some special folder and implement `package:` target
- Detect Alpine Linux in  [https://github.com/packpack/packpack/blob/master/pack/Makefile#L8](pack/Makefile) and include alpine.mk

See  experimental [rumprun.mk](https://github.com/packpack/packpack/blob/master/pack/rumprun.mk#L5) for inspiration.

**Comment by Totktonada** [comment]
It would be good to have this feature to create *.apk packages for extending tarantool docker images (which are based on Alpine Linux).

**Comment by ylobankov** [comment]
For history.

Looks like it was originally implemented in https://github.com/packpack/packpack/pull/91. 
Some fixes have been recently done in https://github.com/packpack/packpack/pull/146 and https://github.com/packpack/packpack/pull/149.
