### ISSUE TITLE
Request Fedora 26 support

### ISSUE THREAD

**Issue by knight-of-ni** [packpack/packpack#78]
Fedora 26 was recently released, and we will need the ability to build ZoneMinder on that distro.

I can easily spawn a new Fedora 26 docker file based of the [existing Fedora 25 docker file](https://github.com/packpack/packpack-docker-images/tree/master/fedora/25) then generate a pull request, but as far as I know, the owner of the docker packpack account will still need to create the image on hub.docker.com. If I am mistaken, or if there is anyway I can do the work for you, let me know.

**Comment by coyote1357** [comment]
Bumping this.  I need fedora 26 support as well.

**Comment by rtsisyk** [comment]
Pushed, please check.

**Comment by coyote1357** [comment]
The command "git clone https://github.com/packpack/packpack.git packpack" exited with 0.
0.80s$ packpack/packpack
+docker pull packpack/packpack:fedora-26
Error response from daemon: manifest for packpack/packpack:fedora-26 not found

**Comment by coyote1357** [comment]
Still not seeing the docker image out there

**Comment by grooverdan** [comment]
https://hub.docker.com/r/packpack/packpack/tags/

<pre>
docker pull packpack/packpack:fedora-26
fedora-26: Pulling from packpack/packpack
....
</pre>

works for me.

**Comment by Totktonada** [comment]
```
$ docker pull packpack/packpack:fedora-26
fedora-26: Pulling from packpack/packpack
<...>
Digest: sha256:4234b839dd80215ce982e3da0653d325c6544cc3629e43cf245450504ee9666b
Status: Downloaded newer image for packpack/packpack:fedora-26
docker.io/packpack/packpack:fedora-26
```

Works for me too. I think the issue can be closed.
