### ISSUE TITLE
Epoch in debian version

### ISSUE THREAD

**Issue by Celedhrim** [packpack/packpack#79]
Hi,

Debian package version allow an epoch value 

From https://www.debian.org/doc/debian-policy/index.html#version

```
The version number of a package. The format is: [epoch:]upstream_version[-debian_revision].

epoch
    This is a single (generally small) unsigned integer. It may be omitted, in which case zero is assumed. If it is omitted then the upstream_version may not contain any colons.
    It is provided to allow mistakes in the version numbers of older versions of a package, and also a package’s previous version numbering schemes, to be left behind.
```

I try to make a custom phpmyadmin package.
The debian phpmyadmin deb has epoch in version.

exemple : phpmyadmin  4:4.6.6-5

Unfortunately , git refuse ":" in tag name.

Could packpack manage this ? maybe choose another character and convert him ?

Thx,

**Comment by Totktonada** [comment]
NB: Thoughts on possible solutions: https://github.com/tarantool/http/pull/164#discussion_r926020122.
