### ISSUE TITLE
Provide versioning and releases via GitHub

### ISSUE THREAD

**Issue by sergeyklay** [packpack/packpack#94]
Given the issue described in https://github.com/packpack/packpack/pull/84#issuecomment-371755389, it would be nice to have versioning so that we can easily switch between versions in case of any problem.  Right now I'm forced to patching packpack directly in  the build process.

**Comment by knnniggett** [comment]
Agreed, it would be nice. In my case, I either patch packpack during the build process or just git checkout a previous commit.
